name       : python-ndg-httpsclient
version    : 0.4.2
release    : 1
source     :
    - https://github.com/cedadev/ndg_httpsclient/archive/0.4.2.tar.gz : d227ab47b05f6e87afdb6b35f05672c3e55d6683a92689b00758eece1af12c66
license    : BSD-3-Clause
component  : programming.python
summary    : Provides enhanced HTTPS support for httplib and urllib2 using PyOpenSSL
description: |
    Provides enhanced HTTPS support for httplib and urllib2 using PyOpenSSL
builddeps  :
    - pkgconfig(python-3.5)
    - python-openssl
    - python-asn1
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install