name       : python-ndg-httpsclient
version    : 0.5.1
release    : 6
source     :
    - https://github.com/cedadev/ndg_httpsclient/archive/0.5.1.tar.gz : 25235c2f67cd97ba385d0103076fa7e0f322a6cb01e490e7d296279243126c55
license    : BSD-3-Clause
component  : programming.python
summary    : Provides enhanced HTTPS support for httplib and urllib2 using PyOpenSSL
description: |
    Provides enhanced HTTPS support for httplib and urllib2 using PyOpenSSL
rundeps    :
    - python-asn1
    - python-openssl
build      : |
    %python3_setup
install    : |
    %python3_install
